### ISSUE TITLE
Convert sandboxID and containerID to distinct types

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#1024]
Currently, `sandboxID`'s and `containerID`'s are "just strings". For example, [`DestroySandbox()`](https://github.com/kata-containers/runtime/blob/master/virtcontainers/api.go#L409):

```go
func DeleteContainer(ctx context.Context, sandboxID, containerID string) (VCContainer, error) { ... }
```

Although all functions that accept `sandboxID`'s and `containerID`'s validate those values, [mistakes can happen](https://github.com/kata-containers/runtime/pull/1019).

We should introduce new types for these IDs so that most issues can be caught at compile time rather than solely relying on runtime checking:

```go
type ContainerID string
type SandboxID string
   :
func DeleteContainer(ctx context.Context, sandboxID SandboxID, containerID ContainerID) (VCContainer, error) { ... }
```

**Comment by gabibeyer** [comment]
I was thinking of putting the type declarations in the runtime/virtcontainers/types/sandbox.go file, since it needs to be used by the store/, hack/, pkg/oci, and pkc/vcmock functionalities, and those all call this types package. Does that seem like an acceptable way of going about it, or is there a more desirable structure?

**Comment by jodh-intel** [comment]
Hi @gabibeyer - could you give an example in pseudo-code?

@sameo, @bergwolf - any thoughts on this?

Also @WeiZhang555 may have input on this topic related to https://github.com/kata-containers/runtime/pull/883.

**Comment by amshinde** [comment]
@gabibeyer Can you post a code snippet here to make things clearer?

**Comment by gabibeyer** [comment]
@jodh-intel @amshinde 
Of course! I was thinking of declaring it in /runtime/virtcontainers/types/sandbox.go for the scope of virtcontainers (since it seems the types package is included in nearly all use cases of ContainerID and SandboxID)
```
package types
.....

type SandboxID string
type ContainerID string
```

then, throughout the runtime code it would be called like: 
types.ContainerID
types.SandboxID

for example, in API.go
```
// DeleteContainer is the virtcontainers container deletion entry point.
// DeleteContainer deletes a Container from a Sandbox. If the container is running,
// it needs to be stopped first.
func DeleteContainer(ctx context.Context, sandboxID types.SandboxID, containerID types.ContainerID) (VCContainer, error) {
	span, ctx := trace(ctx, "DeleteContainer")
	defer span.Finish()

	if sandboxID == "" {
		return nil, errNeedSandboxID
	}
```

Initially I was going to put, for example, the ContainerID type declaration in the runtime/virtcontainer/container.go file, however the 
runtime/virtcontainers/store/vc.go file requires the ContainerID type, but doesn't import the container.go package, and cyclical includes occur if I attempt it :)

Any feed back is appreciated. I can also push a snippet of modified code if that would be easier to read? Thank you for the help!

**Comment by jodh-intel** [comment]
Thanks @gabibeyer. We could just put those types in the existing `virtcontainers/pkg/types/types.go`. Then by tweaking the `import` statement:

```golang
import . "github.com/kata-containers/runtime/virtcontainers/pkg/types"

func DeleteContainer(ctx context.Context, sandboxID SandboxID, containerID ContainerID) (VCContainer, error) {
  // ...
}

```

**Comment by gabibeyer** [comment]
ooo thank you @jodh-intel, I didn't think of that!
I may be completely off, but would it be dangerous to do the import without an identifier (having the '.')? For example there is an Interface type within the types.go file that may shadow the go interface type?

**Comment by jodh-intel** [comment]
@gabibeyer - I see your point. It could indeed be slightly confusing / ambiguous. I'm personally happy with a prefix but maybe we can reduce the existing `vcTypes` to a more minimal `vct` or something to minimise visual fluff / ugliness ;)

Thoughts @sboeuf?

**Comment by sboeuf** [comment]
> after taking a more detailed look, the exporting/capitalization is different, so it probably wouldn't shadow

I don't think you could create an `interface` type as this is a keyword part of the Go language.

About the possible confusion, I would say that as long as we don't have any conflicts and that Go compiler is happy with it, I'm all for the solution:
```go
import . "github.com/kata-containers/runtime/virtcontainers/pkg/types"
```
as it will simplify everything.

**Comment by gabibeyer** [comment]
sounds good, thank you both!

**Comment by gabibeyer** [comment]
@sboeuf @egernst @jodh-intel 
For portions of the code base that don't contain both sandbox and container IDs, should I still modify the types to keep the code consistent, or keep them as strings and make as few changes as possible?

For example, in `virtcontainers/pkg/hyperstart/multiicast.go`
```go
func (m *multicast) buildEventID(containerID, processID string) string {
	return fmt.Sprintf("%s-%s", containerID, processID)
}
```
This function call is relatively unrelated, but would it be worth while to change it to:
```go
func (m *multicast) buildEventID(containerID ContainerID, processID string) string {
	return fmt.Sprintf("%s-%s", containerID, processID)
}
```
or should I only be making changes to places where the issue mentioned above may occur (functions using both sandbox and container IDs)? Personally, I'm thinking of making the changes for consistency sake, but I'm not sure what the "right" thing to do it

**Comment by sboeuf** [comment]
I would say we want to modify it everywhere for consistency across the whole code base.

Now, this raises a more global question about bothering to do some modification to the hyperstart specific code.
@jodh-intel @egernst @amshinde Don't you think we should remove the hyperstart implementation of the agent, hence remove any package that is related to this?

**Comment by jodh-intel** [comment]
I agree - change the types everywhere.

I also agree that there is no point changing the hyperstart and cc code so maybe this issue should be blocked on #1113? In other words, slash'n'burn first then refactor?

**Comment by amshinde** [comment]
Yes, we should be removing the hypertstart and cc implementation. I think we can tackle this right away as I dont think anyone is using this code at all as compared to other features up for discussion such as virtio-blk or virtio-serial. 
We dont run any tests for hyperstart+cc code nor have we added any features in a while.

**Comment by gabibeyer** [comment]
Sounds good, I'll get going on a patch that removes those implementations!

**Comment by sboeuf** [comment]
Thanks @gabibeyer :+1:

**Comment by gabibeyer** [comment]
Hi team, 
I have gotten a little stuck on fixing this issue within the client. After talking with @egernst, it may need to be a bigger discussion. 

There looks to be a few instances within the runtime/cli that containerID and sandboxID are used interchangeably, mostly seemingly due to the OCI spec being unaware of the sandbox. I think we may need to have a discussion about how we want to handle these specific situations (I'll post below some that I found). I am still trying to learn the code base and project, so please correct me where I'm wrong, or give advice in any way :)

First, a few clarifying questions from a new kata user:
1. In the docker case, are sandbox ID and container ID [always|usually|never] the same value?
2. In the kubernetes case, is the sandbox ID the pod ID or the "dummy/pause" container ID, or both?


### instances
from `cli/run.go`
`func run(ctx context.Context, containerID ContainerID, bundle, console, consoleSocket, pidFile string, detach, systemdCgroup bool,`

```go
// delete container's resources
if err := delete(ctx, sandbox.ID(), true); err != nil {
    return err
}
```

however, in `cli/delete.go`, the delete function takes a container ID, not a sandbox ID.
Within the delete function it checks the `containerType`, and either performs a delete sandbox, or delete container depending on the type.

---

There is a similar situation in `cli/start.go` where sandboxID is being passed where ContainerID is expected to run the hook:
```go
return katautils.PostStartHooks(ctx, ociSpec, sandboxID, status.Annotations[vcAnnot.BundlePathKey])`
```
---

A final instance I'm slightly confused on (also probably with my inexperience with all of this, so bear with me) is with the `getExistingContainerInfo` func within oci.go. It seems to be returning the ID of a sandbox, yet is eluding that it is getting container information. I'm not sure if this is a naming thing, or if it goes along with the question of whether these variables should be implicitly called.

which leads me to ask. do you think we should:
1. keep things how they are and implicitly pass strings for container ID and sandbox ID
2. make the modifications to have container ID and sandbox ID be explicit types and then
          a. cast sandboxID to be containerID in situations where they can be the same value 
          b. have different functionalities depending on whether sandboxID or containerID is is being used 

Thank you in advanced for the clarifications and helping me out :)
