### ISSUE TITLE
kata-runtime kata-env not working properly with Firecracker

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#1144]
After following the installation instructions from https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support.
If we perform a `kata-runtime kata-env`, we have the following 
```
/usr/share/defaults/kata-containers/configuration.toml: file /usr/bin/qemu-lite-system-x86_64 does not exist
```

**Comment by jodh-intel** [comment]
I think the static runtime build is looking in the wrong location:

```sh
$ /opt/kata/bin/kata-runtime --kata-show-default-config-paths
/etc/kata-containers/configuration.toml
/usr/share/defaults/kata-containers/configuration.toml
```

Whereas it should probably show something like:

```sh
$ /opt/kata/bin/kata-runtime --kata-show-default-config-paths
/etc/kata-containers/configuration.toml
/opt/kata/share/defaults/kata-containers/configuration.toml
```

**Comment by jodh-intel** [comment]
Ugh - this *should* work:

```
$ make CONFIG_PATH=/opt/kata/share/defaults/kata-containers/configuration.toml
```
... but it doesn't because the katautils refactor appears to have broken this behaviour:

```sh
$ grep -r "var defaultRuntimeConfiguration = "|grep -v CONFIG_PATH 
cli/config-generated.go:var defaultRuntimeConfiguration = "/opt/kata/share/defaults/kata-containers/configuration.toml"
pkg/katautils/config-settings.go:var defaultRuntimeConfiguration = "/usr/share/defaults/kata-containers/configuration.toml"
```

In other words, the value of the `defaultRuntimeConfiguration` the build sets based on `CONFIG_PATH` is no longer being honoured - the only value used is coming from `pkg/katautils/config-settings.go` where the value is hard-coded.

/cc @llifupan.
