### ISSUE TITLE
Is vsock designed as the only access in kata using firecracker?

### ISSUE THREAD

**Issue by clarklee92** [kata-containers/runtime#1194]
As kata users in k8s, we focused on `firecracker` for a long time and I knew that it must with vsock support. The kernel version >= 4.8 is really an obstructive limitation in cloud production ENV, most vendors are still using 3.x kernel. 
 Does the community have a plan like `kata-proxy` for firecracker?

**Comment by devimc** [comment]
cc @mcastelino

**Comment by sboeuf** [comment]
@clarklee92
>Does the community have a plan like kata-proxy for firecracker?

No we don't because there is no other way to communicate with the agent inside the VM. In comparison to QEMU, there's no such thing as virtio-serial support, hence there's no reason to use a `kata-proxy` here. The proxy is only intended to solve the multi connection issue that cannot be handled by the serial port.

**Comment by clarklee92** [comment]
Thank you very much! It seems that firecracker is still far away from production environment.

**Comment by devimc** [comment]
@clarklee92 can we close this issue ?

**Comment by clarklee92** [comment]
> @clarklee92 can we close this issue ?

Of course yes. Thanks again.
