### ISSUE TITLE
Implement the Shimv2 async task model for kata

### ISSUE THREAD

**Issue by lifupan** [kata-containers/runtime#1204]
# Description of problem

The Runtime v2 supports an async event model. In order for the an upstream
caller (such as Docker) to get these events in the correct order a Runtime
v2 shim MUST implement the following events:

#### Tasks

| Topic | Compliance | Description |
| ----- | ---------- | ----------- |
| `runtime.TaskCreateEventTopic`       | MUST                                                                          | When a task is successfully created |
| `runtime.TaskStartEventTopic`        | MUST (follow `TaskCreateEventTopic`)                                          | When a task is successfully started |
| `runtime.TaskExitEventTopic`         | MUST (follow `TaskStartEventTopic`)                                           | When a task exits expected or unexpected |
| `runtime.TaskDeleteEventTopic`       | MUST (follow `TaskExitEventTopic` or `TaskCreateEventTopic` if never started) | When a task is removed from a shim |
| `runtime.TaskPausedEventTopic`       | SHOULD                                                                        | When a task is successfully paused |
| `runtime.TaskResumedEventTopic`      | SHOULD (follow `TaskPausedEventTopic`)                                        | When a task is successfully resumed |
| `runtime.TaskCheckpointedEventTopic` | SHOULD                                                                        | When a task is checkpointed |
| `runtime.TaskOOMEventTopic`          | SHOULD                                                                        | If the shim collects Out of Memory events |

#### Execs

| Topic | Compliance | Description |
| ----- | ---------- | ----------- |
| `runtime.TaskExecAddedEventTopic`   | MUST (follow `TaskCreateEventTopic` )     | When an exec is successfully added |
| `runtime.TaskExecStartedEventTopic` | MUST (follow `TaskExecStartedEventTopic`) | When an exec is successfully started |

For much more info, please see:
https://github.com/containerd/containerd/blob/master/runtime/v2/README.md#events

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by sboeuf** [comment]
Hi @lifupan, from an API perspective, it's not clear why this is needed. For instance, let's take the container creation example. When we ask for a container to be created, send the gRPC request `CreateTaskRequest`. This will return only when the creation of the container is done, so no need for any `TaskEvent` IMO.

Now, are you thinking about implementing this to be able to start the creation of the container when the `CreateTaskRequest` request is received, but return before it's actually completed?
This would be a nice optimization, but at the same time, this would bring some confusion since the caller might think it could call `start` for instance. Also, I think this will add some complexity and potential race conditions. We should maybe talk with containerd folks about this as this should be better if it was internal to containerd, WDYT?

**Comment by lifupan** [comment]
Hi @sboeuf, from the API perspective, the events isn't needed, and the events isn't used to tell Containerd the api's calling status, instead it's  used to notify containerd the container's status asynchronously. Thus some other containerd third plugin's can monitor those async events and do some proper actions on receiving those events. 

Actually some of those events were published in containerd originally, but in order to avoid the race conditions, this commit: https://github.com/containerd/containerd/commit/6468619d736840481ec17ac433e7175eeb8c5ee8 
has moved the event's publishing from containerd to shim.

**Comment by sboeuf** [comment]
@lifupan 
Ok thanks for the explanation. As long as this is not constraining the API, that's fine with me. I don't want to make the API more complex if not strictly needed.
