### ISSUE TITLE
github.com/gogo/protobuf was lost in Gopkg.toml

### ISSUE THREAD

**Issue by teawater** [kata-containers/runtime#1272]
github.com/gogo/protobuf is in vendor but not in Gopkg.toml.
Do we need add it to Gopkg.toml?

**Comment by caoruidong** [comment]
It is in Gopkg.lock. We can add it to toml if we need a constraint on it.

**Comment by sboeuf** [comment]
@teawater 
As long as a package is directly imported by any of the Kata Containers code, we should vendor it explicitly with a constraint on a specific revision.
But I grep'ed the code and I could not find any place where our code was importing this as a Go package, that's why we don't need this to be constrained.

You can see it in our vendoring because it's a sub-dependency.
