### ISSUE TITLE
Setting default configuration with respect to initrd

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#128]
For background see https://github.com/kata-containers/documentation/pull/43#pullrequestreview-107747688 and https://github.com/kata-containers/runtime/pull/98#issuecomment-376431565

We need to decide on the default configuration we expect to "ship" in packages for Kata Containers, and make sure the configuration.toml reflects this.  

@jodh-intel @bergwolf @grahamwhaley @sboeuf

**Comment by grahamwhaley** [comment]
Ideally I'd like a 'developer build' to 'just work' as well without having to hand-massage the toml file (or anything else) - so we could share the 'what is the working default' decision to both the packaging and the repo defaults.

@bergwolf - maybe you could summarise the benefits (and any downsides) of an initrd image for us?

**Comment by jodh-intel** [comment]
I agree that we always want a usable system by default. The problem I think is that there are "multiple" potential usable system scenarios.

So far, if you've been using https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md, you'll have been using a `kata-containers.img` and no `initrd` of course. It **is** worth pointing out though that everything "just works" in the dev guide *because the dev guide builds `kata-containers.img`*. Without that step, the system wouldn't work.

Which is the same as the new world order: without creating an initrd, your system won't work (since `kata-runtime` will see the `initrd="..."` path, attempt to validate it and if it's not blank error if it doesn't exist).

We could of course add instructions to the dev guide on how to build an `initrd` using https://github.com/kata-containers/osbuilder.

But generally, there are two main scenarios to consider here:

- packaged system

  What will `configuration.toml` define?
 
  See: https://github.com/kata-containers/packaging/issues/1

- developer system

  If  a developer is continually running `make && sudo make install` it could get annoying having to constantly comment out `initrd` if they wish to continue to follow todays dev guide.

  But that said, they could copy their preferred config to `/etc/kata-containers/configuration.toml` as that is supposed to be the local version and `/usr/share/defaults/kata-containers/configuration.toml` the pristine" packaged version.

  See: https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md

**Comment by bergwolf** [comment]
I think we can add some text to the dev guide to tell how to build and setup `initrd`. In the meantime, I'm fine if you guys want to change the kata cli to install a `configuration.toml` with `make install` that disables `initrd` by default, as long as we test `initrd` regularly in CI.

As for packaging, I think we should build and ship both `initrd` and `rootfs image` in separate packages. And the runtime package can have a default configuration (either `initrd` or `image`). I believe we will add some user guide somewhere and that one can add details about how to configure `initrd` and `image` based booting.

And to answer the question about benefits of `initrd`, the initrd image is significantly smaller. In my local environment, I have
```
$ls -lh
-rw-r--r--  1 root     root     512M Mar 22 14:03 kata-containers.img
-rw-r--r--  1 root     root      13M Mar 22 23:33 kata-initrd.img
$du -h *.img
144M    kata-containers.img
13M     kata-initrd.img
```

**Comment by devimc** [comment]
the default image depends of the arch and package for example, in x86 .deb and .rpm we use  the image, but for the snaps, initrd is the default because of a limitation in QEMU. Closing issue since we already took the decision about the default configuration.
