### ISSUE TITLE
Latest clearlinux rootfs not working properly

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#1370]
We have several issues with running the latest version of rootfs for clearlinux (firecracker ci is broken) so we need to update to a working one.

**Comment by chavafg** [comment]
I think we should change our approach for using latest clearlinux versions as last week we also got broken when running `yum update` on a centos container.

/cc @jcvenegas

**Comment by jodh-intel** [comment]
I've re-opened the issue as the PR was close (with no explanation), but the problem is still present afaics.

Since Clear currently produces two releases per day, we need to decide how to balance the following requirements:

- Staying as current as possible.
- Minimising *manual* updates to the [versions database](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L137).
- Not getting broken by very recent changes.

@bryteise - any thoughts on the best approach for us? I have noticed btw that Clear is still using Kata 1.5.0, but 1.5.1 was released a couple of week ago:

- https://github.com/clearlinux-pkgs/kata-runtime/blob/master/Makefile

What we may have to do is update the version of Clear we use weekly maybe. Ideally, that would be done by having a zuul job auto-raise a PR to update the versions database for the latest version of Clear that passes all our tests.

**Comment by bryteise** [comment]
Oh, thanks for poke on updating kata. @phmccarty could we look at trying to get the kata ecosystem updates to be run automaticly?

Would it be possible to have your CI system run a job that'll take the latest Clear Linux release and try to validate a known good kata with it (it can run weekly if that makes sense for you). If that works then the Clear version used to test would get updated.

**Comment by bryteise** [comment]
I think that's what you were saying in your suggestion anyway but that seems pretty idea to me.

**Comment by jodh-intel** [comment]
Thanks @bryteise - yes, that sounds like the best plan if we can automate raising the PRs too ;) I think this is something Zuul might be able to trigger for us.

/cc @chavafg, @grahamwhaley.
