### ISSUE TITLE
CPU and Mem consumption is higher than expectation in high density scenario(more than 1k kata containers in one host)

### ISSUE THREAD

**Issue by zhiminghufighting** [kata-containers/runtime#1375]
# Description of problem
CPU and memory consumption higher than expectation
HW config:
CPU: 96 core;
Mem: 384G;

Actions:
launch 1k-1.5k busybox kata containers in shell status in the server;
Mem consumption is above 150 - 200M per containers;
CPU consumption of all the kata container is 30%- 50% of total CPU resource;

# Expected result
Memory footprint per kata container is lower than 100M;
CPU consumption of all the kata container is lower than 20% of total CPU resource;

# Actual result
launch 1k-1.5k busybox kata containers in shell status in the server;
Mem consumption is above 150 - 200M per containers;
CPU consumption of all the kata container is 30%- 50% of total CPU resource;

---
kata version: kata 1.4
Notes: customer wouldn't like to show all the config parameters.

**Comment by zhiminghufighting** [comment]
@egernst @grahamwhaley @jodh-intel @mcastelino  the expected result is a consideration from real business purpose. Even we can't give the mitigation plan now, it is a feedback from real user scenario.

**Comment by jodh-intel** [comment]
Hi @zhiminghufighting - thanks for raising. Clearly, it's going to be rather hard to diagnose the issue if the user is not able to provide full details to us.

However, here are a few things to consider:

- Are the containers "long-running"? It sounds like they are all running `busybox sh` ?

- When was the memory consumption data collected? Immediately after the containers started or some time later? If the former, is there a difference if the memory snapshot is taken later?

- How / where are the cpu / memory consumption figures being collected? I'm assuming they are being collected on the host side?

- Has this behaviour changed since the last version of Kata the user tried? In other words, is the Kata 1.4 behaviour worse in their particular scenario than with say Kata 1.3.1?

- Has the user tried running / compared the results they are seeing with:
  - the latest stable version (`1.5.1`)?
  - the latest 1.4 branch version (`1.4.3`)?
  - the latest packaged and numbered version (`1.6.0-rc1`)?

- Is the user running with the default configuration (no changes to `configuration.toml`)? If they have changed the default configuration, does resetting back to the defaults make a difference?

- Other config questions:
  - Is the user running with debug enabled?
  - Is the user running with vsock enabled?

- What architecture are they running on?

- Is the user running with the [KSM throttler](https://github.com/kata-containers/ksm-throttler) active?

I understand that you may not be able to provide answers to some/all of the above but they might give you / them ideas for areas to look at.

**Comment by mcastelino** [comment]
@zhiminghufighting also will it be possible to run with vsock enabled (i.e. no proxy mode)

**Comment by bergwolf** [comment]
Hi @zhiminghufighting , could you see if this can help https://github.com/kata-containers/documentation/blob/master/how-to/what-is-vm-templating-and-how-do-I-use-it.md ?

Also if CPU/memory consumption is of big concern, please see if you can switch to containerd shimv2 (https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md#containerd-runtime-v2-api-shim-v2-api), which would eliminate kata-shim and kata-proxy entirely. You will need kata 1.5.0+ though. The downside is that it only works with k8s directly. docker doesn't support it yet.

**Comment by zhiminghufighting** [comment]
@jodh-intel thanks for detail answers and clues. My apologies for some info miss before you guys give interesting on it. let me show it below:
1. just running 1k -1.5k busybox sh;
2. collecting cpu/memory consumption is after all containers launched more than 5 mins;
3. they use 1.4 official release;
4. no debug enable;
5. no comparison for 1.3/1/4/1.5;
6. they plan to try shimv2 for next comparison and they are based on k8s so no limits for shimv2 till now.@bergwolf 
7. no vsock enable now; @mcastelino 
Thanks for your inputs! 
By the way, they have a business bar - new solution should be less 10% HW consumption(mainly focus on CPU & Mem) increasement than traditional solution; 
I will keep to track and dig into the perspective of their business mode.

**Comment by grahamwhaley** [comment]
@zhiminghufighting - can I confirm then, these `busybox sh` containers are being launched using k8s?
I ran ~1k containers with `busybox tail -f /dev/null` under docker, and:
- memory footprint was comparible - I will look into the options
- cpu utilisation - my CPUs were 99.75% idle.... which makes me think this might be more to do with the k8s than kata directly. I will try to replicate.

It would be helpful to know if the containers had terminals (`-ti` etc.) enabled etc. - if the yaml to lanuch the busybox containers is available under k8s that would be helpful, to ensure we replicate as close to the reported setup as possible.

**Comment by jodh-intel** [comment]
Ping @zhiminghufighting - ^^ ;)

**Comment by grahamwhaley** [comment]
Hi @zhiminghufighting . I've had real trouble trying to re-create this, even when using `runc` to get a baseline.
I have a bare metal machine with 88cores and 377G of RAM. I tried a deployment of 500 `busybox sh` pods after bumping the kubelet `--max-pods` and scaling up the network IP range to /20. With `runc`, I still only got maybe 250 running pods, and a number of failures for others, and then some odd process fails when killing the deployment as well (but, this could be my local k8s setup... I will see if I can try this in a minikube on the big machine as well....).

> /me notes, [kubernetes says it supports a max of 110 pods per node](https://kubernetes.io/docs/setup/cluster-large/#support) - and whilst I understand there are people running setups modified to support more than this - that does make it potentially significantly harder to re-create the issues locally, especially if we cannot re-create the identical setup or have details.

See #1672 - where there is a patch that I think could be relevant. Can I ask then:
- I presume this Issue is still relevant?
- If so, if the problem can be re-created, can you run `top` and report back what items are consuming the CPUs?
  - I have seen locally two situations where `containerd-shim` and a `kthread` (which appeared to be related to my local ceph storage) were eating 100% CPU - and I'd like to understand where your CPU is being eaten :-)

thanks.
