### ISSUE TITLE
Kata metrics broken in Kubernetes v1.14.0 + Containerd 1.2.5 + kata-runtime shimv2 : 1.6.0

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1488]
# Description of problem

When running with latest Kubernetes, Containerd and Kata, Kata setup as shimv2

Kubernetes v1.14.0 + Containerd 1.2.5 + kata-runtime  : 1.6.0

```
[plugins]
  [plugins.cri]
   [plugins.cri.containerd]
     [plugins.cri.containerd.runtimes.kata]
        runtime_type = "io.containerd.kata.v2"
```

We get incorrect metrics reported (all metrics reported as 0). This means that scaling is also broken.

Early investigation shows that the metrics are being picked up purely from the container cgroups.
Moving QEMU vCPU threads into container cgroups shows metrics being reported properly.

This means that kubelet is not obtaining the metrics via cri, or that containerd is not obtaining the metrics from the kata-shim.

**Comment by sboeuf** [comment]
@mcastelino A few comments there.

I only tried shim v2 and the ability to report metrics through CRI, with CRI-O, so I don't know what was the status for containers with 1.13.

Now, from your description of the issue here, it sounds like we need to identify if this is about the CRI call not being made or if something specific to containerd is broken.

FWIW, when I was testing with CRI-O, I did use the metrics-server to perform the autoscaling, and I was seeing the CRI calls going through CRI-O (I added extra logs for this in CRI-O).

Last thing, let's hear from @lifupan on this too, as he implemented kata-shimv2 basing his testing on containerd.

**Comment by krsna1729** [comment]
> FWIW, when I was testing with CRI-O, I did use the metrics-server to perform the autoscaling, and I was seeing the CRI calls going through CRI-O (I added extra logs for this in CRI-O).

@sboeuf this is with patched kubelet correct? https://github.com/kubernetes/kubernetes/pull/73751

**Comment by sboeuf** [comment]
@krsna1729 no I was changing the CRI socket name for this. Make sure it is not the default that is hardcoded in kubelet.

**Comment by bergwolf** [comment]
ref: cAdvisor is brought in kubelet back by https://github.com/kubernetes/kubernetes/commit/84b0e82db4d485ac474e59a34e4eba878c755944
