### ISSUE TITLE
sandbox dns is not set

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#1603]
kubernetes cri does pass the dns config in `RunPodSandboxRequest.PodSandboxConfig.DNSConfig` and containerd saves it as `resolv.conf` file [in sandbox root dir](https://github.com/containerd/containerd/blob/master/vendor/github.com/containerd/cri/pkg/server/sandbox_run.go#L495). We should pick it up and pass it to the guest via `CreateSandboxRequest` agent grpc.

**Comment by harche** [comment]
@bergwolf thanks, I will send the PR to fix it.

**Comment by amshinde** [comment]
@bergwolf Just to clarify when you say copied into the sandbox root dir, this is actually the root dir of the infra/pod container. So if I understand correctly, currently nothing is broken.
I believe you have created this issue just to support the use case of allowing network access from the agent itself to allow it to download files before any container is started that @harche and @nitkon are interested in. Please confirm. 
cc @egernst

**Comment by bergwolf** [comment]
> Just to clarify when you say copied into the sandbox root dir, this is actually the root dir of the infra/pod container

@amshinde I think it is [the sandbox dir.](https://github.com/containerd/containerd/blob/master/vendor/github.com/containerd/cri/pkg/server/helpers.go#L199). Check files under `/var/lib/containerd/io.containerd.grpc.v1.cri/sandboxes/<sandboxid>/`. We need to see how runc shim makes use of them and copy the behavior.

**Comment by jcvenegas** [comment]
Hey just comming from https://github.com/kata-containers/osbuilder/pull/346 that is 
needed  by https://github.com/kata-containers/agent/pull/625.

@bergwolf I'd like to make clear if setting the DNS in the sandbox adds some value.

Talking with @nitkon  I see the only value for now in https://github.com/kata-containers/agent/pull/625 is just for completeness.

To make this possible, the approach suggested by @nitkon  is to set the `/etc/resolv.conf` in the guest. Because /etc is read mounted, seems that they the file is required to exist from the rootfs (and a PR is in place for it https://github.com/kata-containers/osbuilder/pull/346).

So we are adding as a requirement that the filesystem has a file `/etc/resolv.conf` to be able to modified it, also this require that the `/etc/resolv.conf` remounted to allow write.

My question is we are adding two changes but no value, if the completeness of the sanbox network is an strong reason lets go for it.  If not just lets  close the issue or find a less complex solution.

I think I've seen a suggestion to do something like `/run/etc/resolve.conf`  and mount it in the /etc/resolv.conf so we populate `/run/etc/resolve.conf`. But still I wonder if is still add some value( Probably I am missing something :S )

**Comment by amshinde** [comment]
> @bergwolf I'd like to make clear if setting the DNS in the sandbox adds some value.

Agree with @jcvenegas here, would like to first understand clearly if this fixes something that is broken or addresses a potential bug.
From my understanding, in case of runc, the `/etc/resolve` file is created in the pause container rootfs, so before we try to replicate this, it would be good to get a good understanding of how runc uses this in the first place.

@nitkon If this feature is something that you want for your use-case for getting network access, can you please describe it or atleast give a brief overview if you do not want to get into the details yet.

Once we decide that this adds value, I would rather go with @jcvenegas solution to create a file on `/run/etc/resolve.conf` and bind-mount it to `/etc/resolve.conf`, rather than creating an empty file in the rootfs.

**Comment by nitkon** [comment]
Hello @bergwolf @amshinde @jcvenegas: Following is one of the use-cases where sandbox DNS would be useful.
In order to address the concerns of security-sensitive applications, AMD's SEV(https://developer.amd.com/sev/) and IBM's SVM(https://developer.ibm.com/articles/l-support-protected-computing/) have come up with memory encryption/protection mechanism, where you trust only the VM and everything inside it and not the host. Hence in order to authenticate a few things before launching a container, we would like to fetch some keys for authentication and verification purpose. Hence we would like to set DNS support inside the Kata VM, which already has a network.

**Comment by amshinde** [comment]
@nitkon Sounds good! Thanks for the use-case explanation.
For setting up DNS file in the rootfs, since the rootfs is read-only, I think its best to follow the aprroach that @jcvenegas pointed out.
Let us know if you run into any issues with it.
cc @egernst

**Comment by nitkon** [comment]
@amshinde : The approach suggested above is very similar to this closed [runtime PR](https://github.com/kata-containers/runtime/pull/1825) which I had sent earlier. If the approach looks good, should I re-open that one and the corrosponding [agent PR](https://github.com/kata-containers/agent/pull/590) for review and close other PR's ?

**Comment by amshinde** [comment]
@amshinde Yes, sounds good to me.

**Comment by bergwolf** [comment]
There are actually several part to address, and my suggestions are as follows:
1. how to figure out resolv.conf as being set by `containerd/cri`?
- `containerd/cri` [appends it in infra container's mount slice](https://github.com/containerd/containerd/blob/master/vendor/github.com/containerd/cri/pkg/server/container_create.go#L503). So we need to grab it from infra container.

2. how to pass it to the guest?
- kata-agent `CreateSandbox` API has `dns` field for it.

3. how to set it in the guest?
- Since rootfs might be readonly, similar to @jcvenegas's suggestion, we can save it to `/run/kata-containers/sandbox/resolv.conf` which is a common place for sandbox artifacts, and bindmount it to `/etc/resolv.conf`.

@amshinde @jcvenegas @nitkon please see if we are on the same page. Thanks!
