### ISSUE TITLE
Mixing of 'errors' and 'warnings' in logs on a single line can be confusing

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#1671]
# Description of problem

Whilst debugging a CI failure, I found 'errors' in the runtime logs like:

```
ubuntu-xenial-vexxhost-vexxhost-sjc1-0006078460 kata-runtime[19221]: time="2019-05-10T09:11:36.632910749Z" level=warning msg="load sandbox devices failed" arch=amd64 command=run container=Tw6l1rqSyOtDotqTRevc error="open /run/vc/sbs/Tw6l1rqSyOtDotqTRevc/devices.json: no such file or directory" name=kata-runtime pid=19221 sandbox=Tw6l1rqSyOtDotqTRevc sandboxid=Tw6l1rqSyOtDotqTRevc source=virtcontainers subsystem=sandbox
```

But, that is not really an error, it is a `level=warning`, but containers an `error=xxx` component in it. It is quite confusing when reading the logs - did something important go wrong, or not?

I believe the log comes from:
https://github.com/kata-containers/runtime/blob/master/virtcontainers/sandbox.go#L487

```go
	s.Logger().WithError(err).WithField("sandboxid", s.id).Warning("load sandbox devices failed")
```

The question then is - should we allow mixing of `Error` and `Warning` on the same log line in the kata codebase? If we decide this generates confusing messages, let's do a search and eradicate... (or at least a search to see if it is prevalent)

# Expected result

What I'd really like is very clear errors in the logs just for errors. I know, the current way is to look for `level=error`, but I suspect that is not most peoples first natural search, and they just search for `error`. I don't think we can eliminate all mentions of `error` for non-error cases, as for instance the word appears on some command lines that are logged, but maybe we can do one level better than we do today?

thoughts @egernst @jodh-intel ?
@chavafg - as I'm sure you spend lots of time digging through logs as well....

**Comment by jodh-intel** [comment]
I see your point, but there are seemingly quite a few scenarios where it's worth logging the error, but the scenario is not considered fatal:

```sh
$ cd $GOPATH/src/github.com/kata-containers/
$ find . -name "*.go"|grep -v vendor/|xargs grep "\.WithError("|grep -v "\.Error("|wc -l
86
$ 
```

The `WithError(err)` is worth using even for a `.Warn()` since `WithError()` logs the error with an `error=` tag, whereas if you just do something like `Warn(err)`, you only get the string representation of the error. That loses information since you cannot distinguish `Warn("foo")` from `Warn(err)` which might be useful for tools like the [`log-parser`](https://github.com/kata-containers/tests/tree/master/cmd/log-parser).

I'm sure you're correct that some / most users just search for "error", but you are correct - everyone *should* be looking for `level=error` to find actual errors. They can do that either using `grep`, etc on the raw logs, or running the logs through the [`log-parser`](https://github.com/kata-containers/tests/tree/master/cmd/log-parser) which can convert to text, CSV, TOML, JSON, YAML or XML to make further processing easier.

**Comment by grahamwhaley** [comment]
Fair enough. On from this then, here is an idea - in the CIs, would it be useful to use the `log-parser` tool to extract the `level=error` lines from the logs and attach them as separate log files to the CI artifacts? It might at least make a first level pass of the logs faster. No, I'm not wholly convinced either, but I'd like to explore if there are ways we can make parsing these logs faster for humans...

**Comment by jodh-intel** [comment]
We currently grab all the systemd logs for all components, check them for validity with the log parser in the CI, then attach them as artifacts. So are you saying you'd like us to *also* attach just the errors for each component, or as an additional file or set of files? I'm presuming the latter. One technique would be to run the log parser over all the logs, attach them, and then extract just the errors and attach those as `errors.txt`. Yes, that would be a small amount of duplication (since all the errors are already logged inside each components artifact log file), but having a single timestamp sequenced error summary would be useful to allow you to determine (and determine *quickly* from a single location):

- If all components "survived" (empty file)
- Which components experienced failures.

**Comment by grahamwhaley** [comment]
Yep, the latter sounds good. I can think of a caveat ... we run a number of 'negative checks' in the CI - that is, checking we fail when we should - and sadly I think all those errors will maybe turn up in the logs as well. It might be hard to work out which errors (some of the ones at the end one would presume) belong to the actual CI failure. But, all the errors in date sequence in one file I think might help us track down things faster.
wdyt @chavafg , given I suspect you spend more time in the CI error logs than the rest of us ;-)

**Comment by jodh-intel** [comment]
Yes - I've thought about those before. The best solution I could think of was to inject a new log field when running the unit tests (something like `testing=yes`) so that we could filter out logs like this:

```
time="..." level=error error="ran out of dilithium" testing=yes ...
```

That way, we could ignore all errors logged with `testing=yes`.

**Comment by grahamwhaley** [comment]
Ouch, that's a lot of work in my head. Maybe simpler, we can locate the last runtime invocation (is there an obvious 'first runtime command'?) in the logs, and either clearly mark that in the error stream file, or trim the error file of anything above that point - that is, try to just pull the errros from the last container/pod. Hmm

**Comment by jodh-intel** [comment]
> Ouch, that's a lot of work in my head.

Maybe, maybe not. All the tests would need to do I think is:

```go
savedLogger := kataLog

// Bonus points if we add the test name as a logger field :)
kataLog = kataLog.WithField("testing", "true")
defer func() {
    kataLog = savedLogger
}()
```

That would work for the unit tests (although we want to contrive a way to avoid having to run the above code for every test - either have it run automatically or simply settle for running once in `init()`), but not for integration unless we introduced some sort of "magic" so the particular component knows it's "under test" and adds that flag (we could simply add a `--test-mode` flag to all components that we set when testing at that simply adds an extra log field maybe?)

I'm not sure about last runtime invocation timestamp. The integration tests will be calling the runtime a lot for a single docker operation so we'd have to add these "magic markers" before / after a block of runtime invocations which might not be adequate for what you're trying to do? Also, from what you're saying, the errors file would need to contain both errors and these magic markers (which are not errors).

Any thoughts on all this @chavafg or anyone else?
