### ISSUE TITLE
vfio error cause failed to start privileged kata container

### ISSUE THREAD

**Issue by zhabinecho** [kata-containers/runtime#1712]
# Description of problem

When I create the POD with network interface passthrough to guest, it fails:

> time="2019-05-18T16:52:11.569715264+08:00" level=error msg="failed to hotplug VFIO device" ID=396f4418692cb203212f3c1ef479f14e2a1911b946676dfcae168da4de749a85 error="QMP command failed: vfio error: 0000:5c:00.0: device is already attached" sandbox=396f4418692cb203212f3c1ef479f14e2a1911b946676dfcae168da4de749a85 source=virtcontainers subsystem=sandbox vfio-device-BDF="5c:00.0" vfio-device-ID=vfio-f20ea15af640067e0

> time="2019-05-18T16:52:11.569748867+08:00" level=error msg="Failed to add device" ID=396f4418692cb203212f3c1ef479f14e2a1911b946676dfcae168da4de749a85 error="QMP command failed: vfio error: 0000:5c:00.0: device is already attached" source=virtcontainers subsystem=device

The pci device 5c:00.0 has already pass to guest through qemu, the qemu command as follow

>  -device vfio-pci,host=0000:5c:00.0

Maybe the vfio in container devices don't need hotplug when start privileged kata container?

# Expected result

# Actual result

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by jodh-intel** [comment]
Thanks for raising @zhabinecho.

/cc @amshinde, @devimc.

**Comment by egernst** [comment]
Interesting. /cc @amshinde @bergwolf 

When executing privileged, all the device nodes which exist on the host and exist in the guest are passe into the container.  I believe in your scenario, you hotplug the VFIO device into the virtual machine.  Because the device now exists in the host and the guest, it is automatically passed into the container namespace.  I think the error then occurs since you are trying to pass the device from guest to the container in the guest, as part of the hotplug in the agent code path, but it was already done via priv handling.

Archana, can you PTAL and comment?

**Comment by liwei** [comment]
> error="QMP command failed: vfio error: 0000:5c:00.0: device is already attached" 

It seems the error message came from qemu qmp, I guess the root cause is we attach a vfio device to qemu twice(one as NIC passthrough, the other from privileged device list).

As we already have filterDevices() to filter out devices that have no meaning to pass to the guest, I suggest we make something like a blacklist or whitelist to feed to filterDevices()

Regarding the blacklist/whitelist thing we need more discussion.

**Comment by egernst** [comment]
Ah, I was thinking the error was in the guest. Now that I look closer, you are right @liwei 

For adding devices, perhaps we should check for this particular failure (duplicate)?  I would guess runc just silently allows you to do priv and device passthrough?
