### ISSUE TITLE
shimv2: Add tracing for Kata shimv2 binary

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#1807]
Kata shimv2 does not have any tracing yet. Will be useful to add this.

**Comment by amshinde** [comment]
cc @jodh-intel @lifupan

**Comment by jodh-intel** [comment]
This is an important feature if anyone wants to volunteer to add in the appropriate trace calls?

**Comment by egernst** [comment]
I forgot we didn't have this enabled still.  As we look @ 2.0 Kata and discuss dropping CLI support, we'd effectively be dropping tracing support since shim-v2 does not yet support tracing.

I spent a couple of minutes looking at the CLI tracing and thinking about equivalent utility in shim-v2.

Today a span is created in CLI [after the sub command is parsed](https://github.com/kata-containers/runtime/blob/bdcd2dde30a6ae3a092c3223c93ad50277b2a249/cli/main.go#L345-L356). 

As the comments suggest, this is helpful in making sure the first span is the name of the command being handled. For `shim-v2` configuration of Kata, the runtime is a long running process. I think we'll want to start a new span for each [task-service handler.](https://github.com/kata-containers/runtime/blob/bdcd2dde30a6ae3a092c3223c93ad50277b2a249/vendor/github.com/containerd/containerd/runtime/v2/task/shim.pb.go#L2042-L2060)

**Comment by jodh-intel** [comment]
@egernst - yes, that sounds good to me.

We need to decide if tracing is a release blocker for 2.0 too (if so, this issue should be labelled `release-gating`): we have this work item plus I'm still having problems with https://github.com/kata-containers/kata-containers/issues/60. 

/cc @amshinde, @gnawux.

**Comment by egernst** [comment]
@jodh-intel - I'd say that this is necessary for 2.0 as well; I'm naively hopeful that this isn't too long of a task, and that we'd be able to put this in for 1.12, as well as up to 2.0. 

Based on that -- no concerns with marking this as 2.0 blocking, other than the fact that it doesn't exist in 1.x...

**Comment by bporter816** [comment]
Hi! @tommyrousey, @maomarcus, and @yasv123 and I are students at UT Austin, and we're looking to make some open source contributions over the course of the rest of the year as a part of our virtualization class. Could we be assigned to this issue? And could we have a bit of background on the code changes required for this issue?

**Comment by cmaf** [comment]
Hi @bporter816, thanks for your interest! I'm actively working on this issue. Could you please look at other issues in the backlog that are unassigned? https://github.com/orgs/kata-containers/projects/23#card-43371019

**Comment by cmaf** [comment]
@egernst Regarding your comments on `shimv2` being long running: I handle `StopTracing` in `Delete` and `Shutdown`. Can you clarify what you mean by suggesting that we close the given span at the end of the task-service handling? Do we **not** want to call `StopTracing`?
