### ISSUE TITLE
Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by hahchenchen** [kata-containers/runtime#1908]
Hi, when i use automatic method to install on CentOs7, there came out a bug:
xecStart=/usr/bin/dockerd -D --add-runtime kata-runtime=/usr/bin/kata-runtime --default-runtime=kata-runtime
docker: Error response from daemon: OCI runtime create failed: qemu-vanilla-system-x86_64: -m 2048M,slots=10,maxmem=2015M: invalid value of -m option maxmem: maximum memory size (0x7df00000) must be at least the initial memory size (0x80000000): unknown.

how to fix it?

**Comment by grahamwhaley** [comment]
Ah, @hahchenchen - I believe that is a mismatch between kata and the version of qemu you have. I suspect you are using the default distro qemu, which is probably rather old? It would have helped if you had posted the details from your system (that hopefully the issue template requested you to do?).
/cc @devimc - do you know the details or have a link for the qemu memory alignment requirements, patches etc.?

**Comment by grahamwhaley** [comment]
oh, or, maybe I have mis-read that, maybe it is not alignment. /cc of devimc still stands ;-)

**Comment by devimc** [comment]
the problem is that you don't have enough memory, seems like you are running on an embedded system, please edit the configuration file (`/usr/share/defaults/kata-containers/configuration.toml`) and change the value of [`default_memory`](https://github.com/kata-containers/runtime/blob/master/cli/config/configuration-qemu.toml.in#L78) to 1024 or 512

**Comment by devimc** [comment]
@hahchenchen any update on this?
