### ISSUE TITLE
Time is reset

### ISSUE THREAD

**Issue by cossonleo** [kata-containers/runtime#1919]
# Description of problem
I use kata in dokcer.
When I modify container time, time will be reset after some seconds.

(replace this text with the list of steps you followed)

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by grahamwhaley** [comment]
Hi @cossonleo - that is probably because kata [runs `chrony` inside the VM](https://github.com/kata-containers/osbuilder/pull/265/files) to synchronise the container/VM time with the host....

That was a deliberate decision, as I believe that is what you would see in other (`runc/docker`) container runtimes, as they would be getting their time from the host...

Today I don't believe we have any built in config/switch to let you turn the chrony service off. You could [rebuild your own kata rootfs](https://github.com/kata-containers/osbuilder#rootfs-creation) without chronyd enabled...

**Comment by jodh-intel** [comment]
You could switch to using the initrd-based image by modifying your `configurationl.toml`:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#configure-to-use-initrd-or-rootfs-image

The initrd image runs the `kata-agent` as the init daemon (PID 1), meaning there is no `systemd` and hence no `chrony` service.

**Comment by devimc** [comment]
@cossonleo switch to kata-agent as init `kernel_params="init=/usr/bin/kata-agent"`, better boot time and memory footprint and no chrony :wink:

**Comment by cossonleo** [comment]
@devimc  @jodh-intel  @grahamwhaley  Thanks your helps, I have resolved the problem.
