### ISSUE TITLE
Handle docker -v <volume-name-or-path>:/path where volume is backed by a block device

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#198]
In case of `docker -v <volume-name-or-path>:/path` where the volume is backed by a block device, we should consider passing the block device to the VM.

**Comment by amshinde** [comment]
We have a PR open to handle the case `docker -v <block-device>:/path`, which works well because the block device is not mounted in the guest. 
In the case docker -v <volume-name-or-path>:/path` the volume is mounted on the guest, so mounting this on the guest may lead to issues. This may give us better performance for workloads that rely on volumes.

**Comment by amshinde** [comment]
@bergwolf What do you think? I think mounting in the host and guest may lead to sync issues. Are you aware of any serious issues caused by this. I want to see if this is a viable option for workloads that depend for volumes heavily for their I/O.

**Comment by amshinde** [comment]
cc @egernst @grahamwhaley @sboeuf @laijs

**Comment by bergwolf** [comment]
@amshinde Along side of sync issues, data corruption and kernel crash might happen when we do it.

**Comment by bergwolf** [comment]
@amshinde what we do with devicemapper has the same issue, as long as we mount the block device both on the host and in the guest. I can think of a few cases where you get data corruption or kernel crash even if you do not access the mount point from the host side.
1. ext4 file system has the so called lazy init feature that delays block group initialization to after the device is mounted. If we mount such an ext4 file system on the host and the guest at the same time, there will be host and guest kernel threads reading/writing the same block at the same time, and that can potentially cause data corruption or kernel crash.
2. most Linux block based file systems record the last mount time in the superblock. If we mount a device both on the host and the guest, they will both write to the superblock and can potentially cause fs corruption or even kernel crash.

The above two cases are just what I can think of easily. There might be a lot more. To summary, we cannot do it because such usage is not supported **by design**. And the failures are not easy to verify through some simple tests. OTOH, if we ever deploy in large scale, it will almost certainly happen.

If we really want to do it just for performance advertising, I'd suggest we disable it by default, and add a big warning if people want to enable it in real life.

**Comment by bergwolf** [comment]
And I think the right way to fix this is to teach docker/containerd (optionally) not to mount such block devices on the host but just pass them to the runtime directly.

**Comment by grahamwhaley** [comment]
And, or, we should also think about if any of these mounts are or can be made read only (potentially including the `noload` mount option as well as readonly) (https://linux.die.net/man/8/mount).
That I would expect to prevent actual corruption from two writes happening in parallel. I'm not sure if the readonly mount will get syncs of any writes from the other mount though, so that could still be a problem.

I think what I'd really like to see maybe is some sort of 'matrix' diagram of the types of items we are trying to mount (rootfs, volume, block device etc.), against what our options are (block, 9p, dax etc.) - there are quite a few variables here and I think it is quite hard to keep all factors in ones head...

**Comment by WeiZhang555** [comment]
@bergwolf 
In current implementation of kata, when docker is using devicemapper, container's rootfs  will be both mounted on host by docker and in guest by kata.
In your description, this can cause kernel corruption easily, right? Then I think this is a big design problem.

@amshinde I think we'd better not support this feature describe in the issue. Sometime we will have cases need to mix use 9pfs (for realtime data sync up ) and virtio-blk (for data performance). If we support this interface, I would say it will be hard to distinguish 9pfs usage and virtio-blk usage thus cause more confusion.
In my opinion, `-v /dev/sda:/mnt/` makes kata use virtio-blk is good feature and like magic, but too much magic can bring chaos.

**Comment by stefanha** [comment]
@WeiZhang555 Yes, I think you are right that Kata leaves the rootfs block device mounted on the host.  That is dangerous!

Unmounting the devicemapper target on the host is probably a bad idea without communicating that to the devicemapper storage driver.  Other things might break if the devicemapper target is not mounted on the host.

I have just finished reviewing the virtio-9p vs virtio-blk/scsi modes and think that block device cannot implement the OCI spec and the existing assumptions about containers correctly.  Block devices can handle a subset of the OCI features but it breaks down when the host updates files or when volumes are shared between containers or with the host.

Combined with the security issue that @laijs raised in issue #4, I think that using block devices is not a good idea.   If anyone disagrees I'd love to hear the solutions you have in mind.

**Comment by mcastelino** [comment]
@stefanha 

> Unmounting the devicemapper target on the host is probably a bad idea without communicating that to the devicemapper storage driver. Other things might break if the devicemapper target is not mounted on the host.

What kind of issues do you foresee if we unmount the devicemapper target on the host.

**Comment by stefanha** [comment]
On Wed, May 9, 2018 at 7:37 PM, Manohar Castelino
<notifications@github.com> wrote:
> What kind of issues do you foresee if we unmount the devicemapper target on the host.

Could OCI hooks try to access it?

Stefan

**Comment by WeiZhang555** [comment]
@stefanha I think all things you said are true.

> Block devices can handle a subset of the OCI features but it breaks down when the host updates files or when volumes are shared between containers or with the host.

There's a trade off between compatibility and performance here, with virtio-blk we can gain better performance than 9p, so the idea here is if we don't need to sync up data between host and container simultaneously, we can use virtio-blk instead of 9p for performance.

**Comment by amshinde** [comment]
@stefanha We havent seen any issues with using virtio-blk for rootfs . The rootfs is not really accessed from the host side. I'll check if with unmounting it from the host side we see any issues.

**Comment by WeiZhang555** [comment]
@amshinde I guess unmounting it from host will very likely bring trouble. And we should warn user to not use `docker cp` to copy file from host to container because `docker cp` is actually copying file from host to the mounted dir of devicemapper block, and that can probably crash the host in previous discussion.

**Comment by stefanha** [comment]
@amshinde Please discuss unmounting the devicemapper storage driver folks.  The OCI spec makes no guarantees about ownership of the mount path.  Therefore it's not safe to assume Kata can unmount it.

The cleanest solution is to put the block device path into the OCI config.json instead of a host directory path.  The devicemapper storage driver would not need to mount the block device.  Kata would be safe to access the block device without interfering with the host.  This may require an OCI spec change.

**Comment by bergwolf** [comment]
> The cleanest solution is to put the block device path into the OCI config.json instead of a host directory path. The devicemapper storage driver would not need to mount the block device.

runv has been doing something similar for a long time. The hostpath of rootfs/volume in the container spec may not be a real host path but just an ID referencing extra storage spec defined by runv. It is not compatible to the OCI spec but usable within the kubernetes CRI scope, with the help of frakti. The AddStorage() API @WeiZhang555 is working on would allow similar functionality in the kata side as well.

**Comment by egernst** [comment]
...still an interesting issue.  This'll be hard to support generically.
