### ISSUE TITLE
kata-runtime commands question

### ISSUE THREAD

**Issue by AdamPioneer** [kata-containers/runtime#2131]
# Description of problem
kata-runtime include kata-network\state  to manage container.
But containerd-shim-kata-v2 did not provide these commands.
I using containerd-shim-kata-v2 to create container, then how to check container state and network info like "kata-runtime state" "kata-runtime kata-network" .  

# Expected result
Can check container info like kata-runtime commands

# Actual result

I did not find commands to check container info

**Comment by devimc** [comment]
@AdamPioneer I think you can use the `kata-runtime` to get container's info

cc @lifupan

**Comment by AdamPioneer** [comment]
@devimc 

 Thanks for your info, but unfortunately, kata-runtime will fail，the logs are as follows:
Container ID (xxxxxxx"ID") does not exist

I check the shim v2 code, v2 create sandbox and container using builtin, 
it did not create sandbox and container id mapping to /var/run/kata-containers/containers-mapping/,
then using kata-runtime state command to check container info will fail.


 @lifupan do you have any suggestions?

in addition, why using builtin mode to create container ?

containerd-shim-v2/create.go:

sandbox, _, err := katautils.CreateSandbox(s.ctx, vci, *ociSpec, *s.config, rootFs, r.ID, bundlePath, "", disableOutput, false, **true**)
_, err = katautils.CreateContainer(ctx, vci, s.sandbox, *ociSpec, rootFs, r.ID, bundlePath, "", disableOutput, **true**)



cli/oci.go:
func getExistingContainerInfo(ctx context.Context, containerID string) (vc.ContainerStatus, string, error) {
	cStatus, sandboxID, err := getContainerInfo(ctx, containerID)
	if err != nil {
		return vc.ContainerStatus{}, "", err
	}

	// container ID MUST exist.
	if cStatus.ID == "" {
		return vc.ContainerStatus{}, "", fmt.Errorf("Container ID (%v) does not exist", containerID)
	}

	return cStatus, sandboxID, nil
}

**Comment by lifupan** [comment]
Hi @AdamPioneer 

Since the containerd-shim-kata-v2 used the containerd's shimv2 api, which was different from kata-runtime commandline which was used the containerd shimv1 api. The big deference is that for shimv1, there is no daemon process running to manage the kata containers, and once the container created successfully, the kata-runtime process will exit; but for kata shimv2, there is a daemon process(containerd-shim-kata-v2) which will manage the kata containers, that's why it doesn't need to create the ID mapping and using builtin. 

I don't know how do you run the kata shimv2, using k8s or just using crictl-tools?  Anyway, you can use crictl-tools cmd crictl to get the specific container info, such as:
$sudo crictl info  <container id>  
or
$sudo crictl inspect <container id>

**Comment by AdamPioneer** [comment]
@lifupan thanks
I using k8s to run the kata shimv2.

in fact,  i want to use kata-runtime kata-network command.

Does shimv2（crictl） have alternative command?

**Comment by lifupan** [comment]
For k8s, since the network is managed by cni plugin, and you 'd better not to
do any operations on kata network by kata-network command, otherwise, it would
mangle the network.

So what's you usecase here? 

> Does shimv2（crictl） have alternative command?

For shimv2, we depend on cni plugin to manage the network, thus we hasn't afford any other command.

**Comment by AdamPioneer** [comment]
@lifupan  thanks!

I use as follow command to check network interface.
kata-runtime kata-network list-ifaces "Container ID"

thanks for your info.
