### ISSUE TITLE
containers process always exited automatically with cloud-hypervisor + virtio-fs with dax enabled

### ISSUE THREAD

**Issue by lifupan** [kata-containers/runtime#2307]
# Description of problem

After start the container successully, the container process will exited automatically.
After having a look at the kernel log, it seems there's something wrong with the virtiofs,
the following is the error logs from the guest kernel:

[    3.979527] fuse_setup_one_mapping request failed at mem_offset=0x0 -22
[    3.982067] fuse_setup_one_mapping() failed. err=-22 pos=0x0, writable=0 

If I disabled the dax, it will work.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by lifupan** [comment]
@sboeuf  I noticed that the cloud-hypervisor had supported dax for virtio-fs. Can you take a look on this issue?

**Comment by sboeuf** [comment]
@lifupan I think that's because you're not using the right version of `virtiofsd`. There is one patch of libvhost-user that needs to be carried with virtiofsd to make it work with Cloud-Hypervisor.
Take a look here, this is included in the packaged version of `virtiofsd` binary built by Kata: https://github.com/kata-containers/packaging/blob/master/qemu/patches/virtiofsd/0002-libvhost-user-Fix-the-VHOST_USER_PROTOCOL_F_SLAVE_SE.patch

**Comment by lifupan** [comment]
Thanks @sboeuf, you are right. actually I used the virtiofsd from kata 1.9.2 release, which wouldn't included that patch. After I replaced it with virtiofsd from 1.10.0 alpha release, it does work.
