### ISSUE TITLE
ci: fix issues introduced by Go 1.10

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#249]
Now that our CI has moved to Go 1.10, we need to update one file that is not formatted as the new `gofmt` (1.10) expects it to be formatted.

**Comment by bergwolf** [comment]
Created kata-containers/tests/issues/258 to enforce such a policy.

**Comment by sboeuf** [comment]
@bergwolf the CI always gates any PR from being merged. The problem we have/had here is that we switched the Go version directly on the Jenkins server scripts, and no PR is needed for this...
@jcvenegas @chavafg I think we should make sure that we can setup the Go version from the test scripts we have into github.com/kata-containers/tests, otherwise next Go version switch will cause the same trouble.

**Comment by chavafg** [comment]
yes, sorry for this, we will be using a script on `kata-containers/tests` (see https://github.com/kata-containers/tests/pull/255) that will install the go version in `versions.yaml` file. I see that we have switched again to 1.9 for the moment. We should also update https://github.com/kata-containers/runtime/blob/master/versions.yaml#L136 to 1.9 instead of 1.10, at least until we fix the issues with go1.10.
