### ISSUE TITLE
clh: Enable disk block device hotplug support 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#2570]
**Is your feature request related to a problem? Please describe.**

Cloud-hypervisor recently added support to hotplug block devices this will allow to add instead of use virtiofs for some use cases

**Describe the solution you'd like**

Use cloud-hypervisor API in the case where a block device is added by vircontainers clh implementation.

**Comment by likebreath** [comment]
@jcvenegas I finally made the disk block device hotplug work. I turned that the failing was caused by the wrong hypervisor configuration: we need to use "virtio-blk" instead of "virtio-scsi" with clh. I will need your input on how I should add this config change in the runtime repo. Also, it was fun to follow the code paths from `container` and `device` modules... I finally read quite some code output the clh driver... :)
