### ISSUE TITLE
make check does not work as expected

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#261]
we do static checks in the CI but, when I do make check in the runtime repo , I got a lot of linter warnings, we should skip the or fix the current warns from make check.

**Comment by jcvenegas** [comment]
ping @chavafg

**Comment by sboeuf** [comment]
@jcvenegas please run this with `CI=true` on your machine, it should do the trick ;)

**Comment by jodh-intel** [comment]
Yes, this is actually working as designed:

|Variable set | static checks run |
|--|--|
| &lt;none&gt; | All |
| `CI` | known subset |
| `KATA_DEV_MODE` | same subset as if `CI` set |

I'd strongly recommend setting `KATA_DEV_MODE=true` rather than `CI` though as the latter could be potentially dangerous. See:

- https://github.com/kata-containers/tests#developer-mode
- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L113

Setting `KATA_DEV_MODE` is designed to provide a "CI-like but safe" experience. Without any variables we run all static tests. Some of these might fail as we only enable those linters we know pass on all our repos. The idea is that without variables set we could try to resolve any failures generated by linters we don't currently run for all repos. And once those PRs have landed we could enable an extra linter in `static-checks.sh` so that from that point onwards, with `CI` or `KATA_DEV_MODE` set, the extra linter(s) would run.

**Comment by grahamwhaley** [comment]
Heh, I just ran into similar, but the problem at my end was out of date components. I'll try to PR this into the docs, but basically for me it was:
 - ensure you have a 'clean tree', as the static checks will check all items in your tree. I my specific case that involved getting rid of the old git submodules `cc-runtime` and `runv` that do not get automatically pruned
 - ensure you are using the latest `gometalinter`, as it changes over time, and sometimes either it our our codebase fixes something. If you are not upto date (like the CI, which uses a fresh copy each time I think), you may hit spurious static check failures that our CI does not.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/tests/issues/439.
