### ISSUE TITLE
RFE: Support driver re-binding

### ISSUE THREAD

**Issue by amorenoz** [kata-containers/runtime#2698]
When containers consume devices, they do not expect to perform driver binding. That is supposed to be handled by the orchestration or operation layers. In traditional runtimes, this is not a problem because the way they handle "--device" options does not affect the bus-level driver binding.

However, in Kata treats devices differently. When a device is passed through to a Kata VM using vfio, it appears in the guest and it will be automatically bound to the "default" driver (actually, the one that was modprobed first). This might not necessarily by what the pod expects, which would make the device unusable.

An example would be: a pod wanting to drive a device using userspace drivers (e.g: DPDK), hence expecting the device to be bound to vfio-pci in the guest.

**Describe the solution you'd like**

I think kata should support automatic driver re-binding or override to enable this usecase. The binding itself would have to be performed by the agent, but I think the runtime would have to instruct it to do so.

The agent could support a new [device type](https://github.com/kata-containers/agent/blob/906f7e2e4c52c568f0d990b3c049f863546df848/device.go#L75) for vfio devices.
A new option (e.g: `vfio_driver_override`) could be added to the runtime. If set, it could add the driver information to the `Devices` list in the `CreateContainer` RPC. When that is received, the agent could configure the override.

The limitation of this approach is it would affect all of vfio-based devices.

**Describe alternatives you've considered**

Per-device configuration: Unfortunately, I don't see a clear way of making the decision on a per-device basis. The usecase for this would be a container with 2 devices that wants one of them bound to vfio-pci and the other, to the kernel driver. 

In Kubernetes, it would typically be the DevicePlugin the one to add the DeviceSpecs to the OCI config.json. A way to perform per-[Resource](https://github.com/intel/sriov-network-device-plugin#configurations) could be implemented by:

- Creating a kata annotation that can accept a list of (resourceName, driver) tuples
- When kata runtime is about to create a container, look to see if a [ENV var exists with that resourceName](https://github.com/intel/sriov-network-device-plugin/blob/96cf18486878e8b3a3d9811ee9c94f37b0426d2f/pkg/resources/server.go#L321)
- If it does, look at the PCI addresses listed there and determine what guest PCI address will they be "mapped" to
- Send that all that information to the agent so that it can detect the new PCI device and perform the driver binding

I initially discarded this approach because it too specific to kubernetes and the Device Plugin. However, if the discussion on #2697 concludes that Device Plugin awareness should be added, we could reconsider this option.

Any ideas?

**Comment by devimc** [comment]
> Then, kata-runtime will get the vendor:model information of each vfio device, and if there is matching binding information, send the "driver" information to the kata agent who will perform the driver override.

I see several problems with such approach:

1. The agent needs to wait for the devices to appear, right? 
    1.1 In case of two or more containers, how the agent knows which device to wait? for example a pci device can be hotplugged for `containerA` an a different one for `containerB`
2. All this processes (wait for device, unbind/rebind) must happen before creating the containers in the guest, because the the list of devices must be updated with the devices that were created by the driver (i.e /dev/vfio/4)
   2.1. This new device created by the driver (i.e /dev/vfio/4) will be only visible for the first container? how I can assign a device to `containerB` without making it visible for `containerA` ?

**Comment by c3d** [comment]
@devimc 

> In case of two or more containers, how the agent knows which device to wait? for example a pci device can be hotplugged for containerA an a different one for containerB

Do you mean that the `vendor` and `model` would not be sufficient? Or are you concerned about cases where different containers would specify different drivers?

> 2.1. This new device created by the driver (i.e /dev/vfio/4) will be only visible for the first container? how I can assign a device to containerB without making it visible for containerA ?

Woudldn't such a conflict between containers also exist without driver rebinding? IOW, it's an error to pass the same device to two containers, isn't it?

**Comment by devimc** [comment]
@c3d 

> Do you mean that the vendor and model would not be sufficient? Or are you concerned about cases where different containers would specify different drivers?

When kata hotplugs a vfio device (i.e /dev/vfio/4) it's removed from the list of resources passed to the kata agent, otherwise the agent will create (mknod) this device in the container (this is a task for the guest kernel driver, not for the agent), so the agent is not aware of vfio devices, it doesn't know that it has to wait for a PCI device, having said that, if you pass this information (vendor and model IDs) to the kata agent, the agent won't be able to figure out to which device to wait, does it need to wait for both devices before creating the `containerA` or these devices are for the `containerB`?

> Woudldn't such a conflict between containers also exist without driver rebinding? IOW, it's an error to pass the same device to two containers, isn't it?

I think so, this is an error in the host, unfortunately currently kata doesn't support device cgroup in the guest, so containers can use/share the same devices (yes, I know this is bad, just don't run containers with `-v /dev:/dev`) but support the device cgroup is quite complicated (see https://github.com/kata-containers/runtime/pull/701#issuecomment-419443916), since the agent should be able to wait for the kernel driver to create the devices under `/dev` and update the list of container resources with these brand new devices (i.e /dev/dri/card0 and /dev/dri/card1) before creating the container, this way devices assigned to `containerB` won't be visible in `containerA`, I hope that with this new "driver re-bind" feature, kata finally supports device cgroups.

**Comment by c3d** [comment]
@devimc 

> When kata hotplugs a vfio device (i.e /dev/vfio/4) it's removed from the list of resources passed to the kata agent, otherwise the agent will create (mknod) this device in the container (this is a task for the guest kernel driver, not for the agent), 

Why can't we have the agent keep track in that case? If only because something needs to tell the workload about the guest device name. How would the device name be handed over to the application in the container? (My understanding is that right now, we have to actually scan and rely on PCI vendor/model, not name)

> so the agent is not aware of vfio devices, it doesn't know that it has to wait for a PCI device, having said that, if you pass this information (vendor and model IDs) to the kata agent, the agent won't be able to figure out to which device to wait,

Well, to me there are two distinct inputs:
- The pod manifest gives you (vendor, model, driver) to allow you to rebind.
- The workload receives the actual device name some other way (today, may be env variables), and some additional name mapping may be required there.

So the way I saw it, the agent "stashes" somewhere the (vendor, model, driver) triple, and then when receiving a device that matches, waits for the rebinding to happen. Maybe I'm over-simplifying, because quite frankly I have not explored that much.

That means the agent would have to treat that specially and avoid things like mknod (although I did not understand why doing it would be bad in that case, since we precisely want to expose the device to the container)

> I think so, this is an error in the host, unfortunately currently kata doesn't support device cgroup in the guest, so containers can use/share the same devices

So that may be another reason to keep the info in the agent. Not that we can do much if we detect the situation, but maybe at least log it.

**Comment by amorenoz** [comment]
@devimc 
>    1. The agent needs to wait for the devices to appear, right?
>     1.1 In case of two or more containers, how the agent knows which device to wait? for example a pci device can be hotplugged for containerA an a different one for containerB

I think we can use vendor/model in the runtime for driver mapping. But the agent could get the guest BDF which will make things easier.

If the BDF/driver information is sent in the CreateContainer RPC call, wouldn't that be associated with the right container?

A new devHandler will be needed to handle vfio devices. Such handler could maybe look for the device by the BDF and perform the driver binding or add a uevent listener to do so. What do you think?

Also, driver-specific logic might be required if we want full flexibility. For instance: for vfio-pci, we have to add /dev/vfio/X to the container, for a netdev driver it's adding it to a network namespace, etc.

**Comment by ariel-adam** [comment]
@dgibson David, is this still relevant in your opinion or can we close it?

**Comment by c3d** [comment]
@dgibson This looks a bit stale to me, but related to our recent email discussions. Could you comment. Does that make any sense, or should we just drop this approach completely.
