### ISSUE TITLE
Isolate hypervisor process with cgroups

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#344]
The hypervisor process is responsible of taking care of the VMs, and if a security breach was related to the hypervisor itself, it could give a way for a VM to escape.
In order to increase the security, we should constraint the hypervisor process inside using `cgroups` as much as possible.
For instance, the CPU cgroup can be a simple sum of the number of CPUs needed by the containers running inside the VM.

**Comment by sboeuf** [comment]
Relates to https://github.com/kata-containers/runtime/issues/168

**Comment by jshachm** [comment]
Good issue! 
And besides this, should we do this like what `libvirt` does: put `vcpu thread` and `emulator thread`  into different sub cgroups path.
And maybe we need a good `cgroups operation pkg` ,if we want to implementation features.
What do you think? @sboeuf  :-)

**Comment by sboeuf** [comment]
@jshachm can we get this granularity (I mean identifying the threads) given that we are using the Qemu command line and not the libvirt package in our case ?

**Comment by jshachm** [comment]
@sboeuf 
Yep, AFAIK, `vcpu thread` has some characteristics like ` /proc/xxx/task/comm` contains `vcpu` etc. 
We can use these to split them.

Talking about `cgroups control pkg`. Can we use [`containerd/cgroups` ](https://github.com/containerd/cgroups) since it is a native `cgroups pkg` used in `containerd`.

cc\ @WeiZhang555   @egernst  @jingxiaolu

**Comment by jingxiaolu** [comment]
Discussed with @jshachm @WeiZhang555 offilined, we can work on this issue.

I do agree with @jshachm that we should introduce a pkg to maintain cgroup handlings in `runtime` :-)

**Comment by sboeuf** [comment]
A global package sounds like a good idea. About the step to approach this issue, I think we can split into sub issues, with first constraining the qemu process into some cgroups, and as a second step, use a finer granularity and identify specific threads as suggested by @jshachm.

**Comment by jodh-intel** [comment]
Let's also be careful to make the code generic enough to handle isolating any hypervisor, not just qemu :)

Further, we need to ensure that we can unit test this fully by launching a fake hypervisor which runs the equivalent of the following so we can check to ensure the code dtrt:

```
$ (ls -l /proc/self/ns; cat /proc/self/cgroup)
```

**Comment by jingxiaolu** [comment]
Refactoring cgroup handling in runtime is almost ok, I hope a draft can be sent to you in next few days :-)

What I've done:
1. use `runc/libcontainer/cgroups` instead of `containerd/cgroups` for better input validation
2. add a cgroup manager to `sandbox` for handling cgroups
3. put cgroup handling in `sandbox` level

Thanks for you guys :-)

**Comment by sboeuf** [comment]
Thanks @jingxiaolu, looking forward to the draft :)

**Comment by sboeuf** [comment]
@kata-containers/runtime This issue should be looked at in order to increase security around the VM process. Please assign it to yourself if interested in it.

**Comment by jingxiaolu** [comment]
Sorry for leaving long time for paternity leave, I'll speed up on this issue.
