### ISSUE TITLE
virtcontainers: Remove unnecessary kernel parameters for ppc64le

### ISSUE THREAD

**Issue by nitkon** [kata-containers/runtime#360]
# Description of problem
pci=lastbus=0 is an intel only feature. POWER does not use it. So we can remove this option for ppc64le.
Reference: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/kernel-parameters.txt#n3058
{"iommu", "off"} can also be removed.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/kernel-parameters.txt#n1699
{"cryptomgr.notests", ""}, and {"net.ifnames", "0"}, should improve the boot times.

# Expected result
NA

# Actual result

NA

---

**Comment by grahamwhaley** [comment]
We used to have a patch to disable those crytpo tests:
https://github.com/clearcontainers/linux/commit/3dda8068f4b6c2b66d4b22338032d0c14d20bceb

But, iirc, in a recent round of boot time evaluation (by @devimc iirc), we could not measure a difference in boot time.
I would be **very** interested in seeing measurements and results for making this change. I believe it will make a difference - but - maybe that difference gets hidden by parallel actions on a multi-threaded SMP VM boot. Since we switched recently iirc (also by @devimc ;-) ) to a single vCPU at boot, maybe we will now see a difference?

Soo.... the three rules of optimisation then - measure, measure, measure :-) (or is that [two rules?](https://en.wikiquote.org/wiki/Michael_A._Jackson#Quotes_about_Michael_A._Jackson) )
