### ISSUE TITLE
Can multiple containers run in one sandbox?

### ISSUE THREAD

**Issue by bekars** [kata-containers/runtime#390]
# Description of problem

In our project, we want run multiple same containers, they owned by one tenant, in one sandbox.

1. Is this scope implemented or not in kata project ? 
2. Can it support Docker or Kubernetes?

I don't find any documents to config such environment. I appreciate for your answer.

**Comment by sboeuf** [comment]
Hi @bekars, running multiple containers from one tenant inside the same sandbox is the natural way to handle things in Kubernetes. And because Kata Containers does support Kubernetes if used with CRI-O or CRI-containerd, you can simply run several containers in the same pod, they will end up running inside the same virtual machine in case of Kata.

About Docker only, there is no such concept as sandbox/pod, the container is the highest level of granularity and that's the reason why this case cannot apply to Docker.

**Comment by WeiZhang555** [comment]
Kata containers use annotation from runtime spec to specify many containers in single POD, as docker has no way to pass the annotation down to kata-runtime level, there's no way to compose a POD in Docker scenario. 

But @jshachm from Kata and Huawei team is trying very hard to upstream a patch to docker for supporting passing the annotation: https://github.com/moby/moby/pull/37262 ,  I believe in near future, you will be able to create a POD with docker after backporting a very small docker patch. 

Cheers :-)

**Comment by egernst** [comment]
@bekars - This is stale at this point, and I believe we've answered your query.  Let me know if you have further questions.
