### ISSUE TITLE
Using different hypervisors?

### ISSUE THREAD

**Issue by Kuvesz** [kata-containers/runtime#444]
My question's in the title. Is it possible to use a different hypervisor (specifically I'm thinking about bareflank or something very lightweight like that) instead of qemu?

**Comment by jodh-intel** [comment]
Hi @Kuvesz - in principle "yes" since we've taken care to ensure the code is structured to allow for new hypervisors. In practice, you'd need to add support for the new hypervisor in a couple of places:

- Minor changes to the runtime:
  - Change `cli/config.go` to support something like `[hypervisor.bareFlank]` in `cli/config/configuration.toml` by implementing a `newBareflankHypervisorConfig()` function like:
    - https://github.com/kata-containers/runtime/blob/master/cli/config.go#L291

- Changes to virtcontainers:
  - Create a new `HypervisorType` for the bareFlank hypervisor in `virtcontainers/hypervisor.go`.
  - Implement the `hypervisor` interface for bareFlank:

    - https://github.com/kata-containers/runtime/blob/master/virtcontainers/hypervisor.go#L491..L506

    - For reference, the qemu implementation is in `virtcontainers/qemu.go`.

/cc @sboeuf, @sameo, @bergwolf, @markdryan, @jon.

**Comment by Kuvesz** [comment]
Thanks, I'll look into it than. :)

**Comment by jodh-intel** [comment]
Please do let the community know if you'd like help with this by the way - find us on irc/slack/ML:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#contact

**Comment by Kuvesz** [comment]
@jodh-intel Of course, but I'm still looking into bareflank, if it can be even used as a replacement for qemu I'll let you people know.
