### ISSUE TITLE
Test Kata on baremetal AWS

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#45]
Test kata-runtime on a baremetal AWS node, documenting any issues observed.

**Comment by raravena80** [comment]
This might be a bit challenging initially in terms of costs, the bare metal instances are pretty hefty. 

https://aws.amazon.com/blogs/aws/new-amazon-ec2-bare-metal-instances-with-direct-access-to-hardware/

I'm not sure on the pricing yet, since they are in preview atm.

We can check if c5 instances work (which would be more cost effective).

https://aws.amazon.com/blogs/aws/now-available-compute-intensive-c5-instances-for-amazon-ec2/

**Comment by hwinkel** [comment]
there are other bare metal provider out there. I my experience the folks at packet.net is very supportive for such kind of resources.

**Comment by egernst** [comment]
no issues observed - works just fine!

**Comment by ydjainopensource** [comment]
Since we are testing on AWS, it makes sense to test on other cloud providers as well. Getting access to baremetal instances for testing is difficult though. Lets create a separate issue for tracking this.

**Comment by hnwolf** [comment]
Hi, could you please share test document with me, I am volunteer to test on other cloud provider's bare metal.

**Comment by grahamwhaley** [comment]
Hi @hnwolf - welcome!
Probably the easiest way to test is going to be running the same tests that our CI system run.
You can see those tests, and some documentation on the requirements and how to run them, over at https://github.com/kata-containers/tests#run-the-kata-containers-tests
I'll pull in @chavafg @GabyCT so they can give any more input on things to look out for.
Don't hesitate to come back here and ask questions!

**Comment by chavafg** [comment]
Hi @hnwolf, the link @grahamwhaley posted should be a good start. If you find any issue or something not well documented, please let us know by opening an issue in the tests repo. 

Thanks.

**Comment by hnwolf** [comment]
Thanks for your comment, I will do that.
