### ISSUE TITLE
runtime API revisit

### ISSUE THREAD

**Issue by laijs** [kata-containers/runtime#46]
On this week’s meeting, The kata-community discussed the merging and @ganwux made a short [presentation](https://docs.google.com/presentation/d/1BZvRQdJUnSmaeaKgJPS-E9RFTFb7qsM7ybexSt4zxX0/edit).

We compare the API(#32) from the requirement(#31) and the APIs of virtcontainers, they don’t have fundamental conflicts.

The only critical difference is that virtcontainers operations(APIs) are pod-name based. Actually, these operations are mixtures(wrappers) of pure Pod operations and Persistence(resourceStorage) operations. In some cases, the mixture-style APIs are convenient. For example, when these APIs are used on oci-runtime-cli, every new cli command needs to restore sandbox object/interface from Persistence and do the operation which fit to these mixture-style of APIs.

To meet the requirements and to make the APIs to be cleaner, the mixture-style of APIs need to be split into pure sandbox APIs and Persistence(resourceStore) APIs, they will be the two main APIs sets of the library.

Pure sandbox operations(APIs) take Sandbox(golang interface) as its receiver. The user can call them multiple times with or without interacting with Persistence(resourceStorage).

The virtcontainer' resourceStorage(Persistence) interface needs to be exposed and become as a part of the APIs. The user can implement it on database(fratki/hyperd), filesystem(cc-runtime) or even memory.

So the major APIs should be pure sandbox APIs and Persistence APIs.

Another important difference is that, the proposed APIs (#32) have a minimal Storage/Network driver support and operations. It is just because the library should also support qcow2/ceph, enlightened/bridged networks (without net namespace) and some other complex Storage/Network. Like the docker world where Storage/Network driver are not a part of runtime, Storage/Network operations here are not a part of the CreateContainer()/RunContainer() either. The this separation is also important for performance. Drivers’ operations take time, qemu hotplugs take time and guest kernel hotplugs take time, and the separation-style API can make them run parallel: a device can be hotpluged in earlier as soon as it driver’s preparation is done, while the other driver’s preparations can still be ongoing.

Another two differences are the stream IO and detecting exceptions(agent crash, vm crash, qemu crash, proxy crash…). These APIs are very easy to be added later. The operation for detecting exceptions is almost useless on oci-runtime-cli cases, because these is no long running process to call the API. But they are useful for CRI (fratki/hyperd).

The last and the controversial difference is the exposure of the Agent/VM interfaces and the allowing the user to use their own implementations. The exposure makes the library users can configure out the proxy/shim processes which are unneeded in some cases (especially when CRI). The exposure makes the library users can easily add different hypervisors and vm-factories(vm-cache, vm-clone ...). Many people prefer them not to be exposed, we can add many implements in the library instead. I totally admit it as I don’t want this differences blocks our merging progress.

**Comment by bergwolf** [comment]
cc @sboeuf @sameo @WeiZhang555 @tallclair @jessfraz @amshinde @jodh-intel PTAL.

**Comment by sameo** [comment]
@laijs @bergwolf @sboeuf 

> Pure sandbox operations(APIs) take Sandbox(golang interface) as its receiver. The user can call them multiple times with or without interacting with Persistence(resourceStorage).

That makes sense to me, and I can see how that makes a significant difference for a pure CRI implementation. We'll add that to the top level virtcontainers API.

> The virtcontainer' resourceStorage(Persistence) interface needs to be exposed and become as a part of the APIs. The user can implement it on database(fratki/hyperd), filesystem(cc-runtime) or even memory.

Is the Frakti implementation proprietary? If not, in the short term I'd prefer to have those persistence implementations kept internal. We need to implement a robust virtcontainers plugin support for external hypervisor drivers, and we could extend that to persistence drivers if needed.

> So the major APIs should be pure sandbox APIs and Persistence APIs.

The sandbox based API makes perfect sense, I'd like us to consider keeping the persistence one internal for now.

> Another important difference is that, the proposed APIs (#32) have a minimal Storage/Network driver support and operations.

Ok, here we need a few more explanation to understand how we can and if we need to address that with virtcontainers.
I'm trying to understand the reasons for exposing the `addStorage` and `addNetwork` APIs...My understanding so far:
* `addStorage`: This is for attaching a volume to a sandbox/pod that somehow would be eventually mounted in the container mount namespace. And this is needed in order for e.g. Frakti to attach ceph volumes to a sandbox while creating it so that eventually containers within that pod could quickly mount it in their mount namespace? If so couldn't we then add a `Storage` field to vc's `PodConfig` and handle the attachment from `CreatePod`/`StartPod`?

* `addNetwork`: I'm having more trouble understanding this one, sorry. Is the goal for that one to add an interface to the pod? Would you mind describing a concrete example that could not be handled as part of the `CreatePod`/`StartPod` routines?

> The last and the controversial difference is the exposure of the Agent/VM interfaces and the allowing the user to use their own implementations

@jon pointed out a good use case for that one, for proprietary VMMs. So I think there's some value to it . But I think for properly exposing those interfaces, the first step would be to define those as clean virtcontainers plugins that could be added dynamically and would register new e.g. hypervisor types. Would you agree with that assertion?

**Comment by sameo** [comment]
I put some slides together as a proposal for extending the virtcontainers API to address those gaps:

https://docs.google.com/presentation/d/1dbGrD1h9cpuqAPooiEgtiwWDGCYhVPdatq7owsKHDEQ/

I'll present them at today (03/12) arch committee meeting.

**Comment by sameo** [comment]
@laijs 
> The exposure makes the library users can configure out the proxy/shim processes which are unneeded in some cases (especially when CRI)

I believe this could simply be done through a virtcontainers pod configuration. Today, one can already configure pods to not use any proxy or shim at all.

**Comment by egernst** [comment]
@laijs - I opened a few issues today covering the API extensions.  Can we close this and move to defining the API per "area" in these issues?
