### ISSUE TITLE
Which Kubernetes version(s) should we officially support?

### ISSUE THREAD

**Issue by chavafg** [kata-containers/runtime#489]
Currently we are testing kubernetes 1.10 in our CI, with cri-o 1.10. But the newest version 1.11, was released a couple of weeks ago. 
We are also testing OpenShift 3.9 (which uses k8s 1.9) using cri-o 1.9 on our Fedora jobs.

Which version(s) of kubernetes should we support? 
Currently I think that there is no statement of which version of k8s we support, we only have the reference of what we use in the CI here: https://github.com/kata-containers/runtime/blob/master/versions.yaml#L163 

We have mainly two options here:
1. Support only the latest version.

2. Support the versions that CRI-O support? https://github.com/kubernetes-incubator/cri-o#compatibility-matrix-cri-o---kubernetes-clusters 
    - This will require more CI jobs. 

Also to take in consideration, we currently do some basic testing for k8s, but in the near future we should add e2e testing.

/cc @sboeuf @sameo @tallclair @amshinde @gnawux @egernst

**Comment by chavafg** [comment]
btw, I've just made some local testing using k8s 1.11.0 and crio 1.11.1 and with some minor tweaks in the CI scripts, all our tests passed correctly.

**Comment by sboeuf** [comment]
@chavafg thanks for summarizing the issue here. I think that from the discussion during the Arch Committee, we said that supporting the latest stable version of Kubernetes should be enough. We can still decide later to add more backward compatible versions, but we would need more CI resources for that.
That's a very good news that we have no regressions moving to k8s 1.11, and I think we should make this move happens rather sooner than later.
Also, I completely agree that we should extend our CI by integrating the test suite from k8s. This will bring wider coverage without the need for us to write new tests.

**Comment by bergwolf** [comment]
Does kubernetes have a concept of long-time maintaining releases? If so, we should consider sticking with the same release as kubernetes community does.

**Comment by gnawux** [comment]
As Tim said, kubernetes officially supports two previous releases.

**Comment by tallclair** [comment]
Correction: we Kubernetes supports 3 minor releases - latest, and 2 back (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew)
