### ISSUE TITLE
kata does not support docker shared PID namespace

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#493]
With docker, Kata does not support starting a Kata container which shares a PID namespace.

example:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
a33e4ce87bef        nginx               "nginx -g 'daemon of…"   11 minutes ago      Up 11 minutes       80/tcp              frosty_kepler
$ docker run --runtime=kata-runtime --pid=container:a33e4ce87befabaf44e328c451bfe24ad380a8f4aa7b504c9945c8baf5657038 -p 8080:8080 brendanburns/topz:db0fa58 /server --addr=0.0.0.0:8080
```

Expectation:  topz would be able to monitor the processes running in container ```a33e4ce87bef```.  

Result: topz is running within a VM, and has no way of sharing PID ns with something on the host (or in another VM).  No processes are reported.

This is a common design pattern (monitoring sidecar), but cannot work in the docker scenario for Kata.  I don't expect this to be fixed - this is just a known limitation.

 Note, this is fine in K8S context where each container is within the same pod (VM).

**Comment by grahamwhaley** [comment]
It might be worth adding that to the [limitations documentation](https://github.com/kata-containers/documentation/blob/master/Limitations.md#architectural-limitations). Then. Maybe under the architectural limitations section, or if we are missing a section around joining an existing container namespace, creating a new section for that?

**Comment by bergwolf** [comment]
Or maybe we can try to translate `--pid=container:a33e4ce87befabaf44e328c451bfe24ad380a8f4aa7b504c9945c8baf5657038` into pod id a33e4ce87befabaf44e328c451bfe24ad380a8f4aa7b504c9945c8baf5657038 and create the requested container in the specified pod instead?

**Comment by sboeuf** [comment]
@bergwolf we could always try to find a way to hack this, and your proposal might work, but at the same time, this would modify completely the security between those containers. Basically, the user is asking for sharing the pid namespace between those containers, but at the same time, because he's using Kata, he would expect those containers to run into separate virtual machines, which will not be the case here.
What I am saying is, this is feasible but if people really want this kind of things, they should use CRI layer to make sure this is handled properly. I would put a low priority on this.

**Comment by amshinde** [comment]
@egernst @grahamwhaley We should add this as a limitation stating this is not possible for other namespaces as well ipc, net etc
