### ISSUE TITLE
virtcontainers: Make sandbox manage VM CPUs. 

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#833]
Today the VCPUS resources are managed by the container.go in virtcontainers API but the VM resources should be managed by the sandbox. The container only is reponsible to update namespaces and cgroups.

**Comment by jodh-intel** [comment]
I think you just won the *"issue with the longest title award"* @jcvenegas - :trophy: :fireworks:

**Comment by WeiZhang555** [comment]
@jodh-intel Definitely! :laughing:

**Comment by jcvenegas** [comment]
@jodh-intel @Weichen81  lol thanks for the award @jingxiaolu  I reworked the sandbox resources in https://github.com/kata-containers/runtime/pull/793

**Comment by egernst** [comment]
@WeiZhang555 @jcvenegas I agree -- vCPU should be handled at Sandbox level, not at container level.  

Having said this, I think it still makes sense to track CPUs requested in the context of containers, since we will still constrain in the VM here, and since we may have specific cpusets which we'll want to maintain at the container level (see https://github.com/kata-containers/runtime/issues/878)

**Comment by WeiZhang555** [comment]
>In summary, I think we need to keep track of the resources on a per container basis, but should pool this together when making and changes to QEMU.

Yes, we need to track this. Currently kata saves container OCI config.json so I think this is possible.
