### ISSUE TITLE
Exec format error (ELF 32-bit)

### ISSUE THREAD

**Issue by blurayne** [kata-containers/runtime#886]
# Description of problem

ELF 32-bit LSB executable cannot be loaded right now. ELF-64 works fine. Will it be available some day or is it not on the schedule?

$ docker run -it --runtime kata --rm snx:latest /usr/bin/snx --help  

# Expected result

Command is run and setuid 

# Actual result

bash: /usr/bin/snx: cannot execute binary file: Exec format error

**Comment by grahamwhaley** [comment]
Hi @blurayne - thanks for reporting.
I strongly suspect that is because, by default, our VM kernel used inside QEMU/KVM is not configured to support Intel 32bit executables.
Specifically, something around the area of the kernel `CONFIG_IA32_EMULATION` and `CONFIG_X86_X32` maybe - but, I'm no expert in that area of Intel 32bit compat and elf's...

I doubt we will enable 32bit support for our kernels by default, as I suspect it is such a rare case that we'd rather not take the overhead hit on our memory footprint. What can be done though is to build a new kernel with those options enabled using the [osbuilder repo](https://github.com/kata-containers/osbuilder), and replace the default kernel file in your installation.
If you would like to try that @blurayne and want any input, just ask and we'll see what we can do. This would be a good thing to add both to our [limitations page](https://github.com/kata-containers/documentation/blob/master/Limitations.md) and also as a ['howto'](https://github.com/kata-containers/documentation/tree/master/how-to) guide on how to enable (which configs to set etc.).

**Comment by blurayne** [comment]
Probalby here https://github.com/kata-containers/packaging/tree/master/kernel.

I'll give it a try.

**Comment by grahamwhaley** [comment]
I've a feeling, if you use osbuilder, then it might pull the configs in from the packaging repo at https://github.com/kata-containers/packaging/tree/master/kernel/configs
@jcvenegas @devimc - can you clarify?
