### ISSUE TITLE
kata-runtime should report stats to crio

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#891]
# Description of problem

crictl stats reports stats for all runc containers but does not report stats for kata launched container. These stats are then reported to core-metrics and used for horizontal auto scaling. Without support for stats we cannot see kata pod metrics or scale kata pods.

# Expected result

crictl reports kata stats. 

# Actual result

No kata pods or containers reported in stats

# Component details
```
kubelet --version
Kubernetes v1.12.2

sudo crio --version
crio version 1.12.0
commit: "774a29ecf6855f2dff266dc2aa2fe81d7d964465"

kata-runtime --version
kata-runtime  : 1.3.0
   commit   : d895cd0f2dec7cbabfda95846543314565acc70a
   OCI specs: 1.0.1-dev
```

**Comment by sboeuf** [comment]
Some thoughts here:

If the stats come from the cgroups of each container process, then it cannot work for Kata as it is, since we don't constraint the shim process. The `cgroups` constraints are only applied to the QEMU process.

Now the other question is how the pod constraints get updated every time a new container is created, meaning the overall constraint of the pod needs to be updated. I think the CRI implementation, or the CRI caller has to be the one updating the container resources of the container representing the pod. Because if we think about runc, it has no idea that it should update the cgroups of the container representing the pod since it does not have any notion of pods.

I think that before to create a new container in an existing pod, the upper layers update the container resources of the container representing the pod. Once this is done, a new container can be created.

**Comment by egernst** [comment]
The logic is already there in Kata Containers to provide stats on a per container basis. You can see this by running kata-runtime events.

We need to make sure that CRI levels call for this.  Today CRIO uses CAdvisor, which has many old assumptions.  This will also be fixed for containerd once v2shim support is merged.  See https://github.com/kata-containers/runtime/pull/572

**Comment by egernst** [comment]
@mcastelino were we able to check if this is the same behavior with containerd?
